spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
      sns:
        endpoint: http://localhost:4566
      dynamodb:
        endpoint: http://localhost:4566

server:
  port: 8082

payment:
  receipt:
    queue-name: payment-receipt