spring:
  cloud:
    aws:
      region:
        static: us-east-1
      sqs:
        listener:
          max-concurrent-messages: 10
          max-messages-per-poll: 10

payment:
  receipt:
    queue-name: ${PAYMENT_RECEIPT_QUEUE_NAME}