package br.com.developers.payment;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.util.Optional;

@DynamoDBTable(tableName = "payment")
public class Payment {
    @Id
    private PaymentKey paymentKey;
    @DynamoDBAttribute(attributeName = "date")
    private String date;
    @DynamoDBAttribute(attributeName = "value")
     private String value;
    @DynamoDBAttribute(attributeName = "description")
    private String description;
    @DynamoDBAttribute(attributeName = "pix_key_credit")
    private String pixKeyCredit;
    @DynamoDBAttribute(attributeName = "ttl")
    private Long ttl;

    @DynamoDBHashKey(attributeName = "pk")
    @DynamoDBAutoGeneratedKey
    public String getPk() {
        return Optional.ofNullable(this.paymentKey)
                .map(PaymentKey::getPk)
                .orElse(null);
    }

    public void setPk(String pk) {
        if(this.paymentKey == null) {
            this.paymentKey = new PaymentKey();
        }
        this.paymentKey.setPk(pk);
    }

    @DynamoDBRangeKey(attributeName = "sk")
    public String getSk() {
        return Optional.ofNullable(this.paymentKey)
                .map(PaymentKey::getSk)
                .orElse(null);
    }

    public void setSk(String sk) {
        if(this.paymentKey == null) {
            this.paymentKey = new PaymentKey();
        }
        this.paymentKey.setSk(sk);
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getPixKeyCredit() {
        return pixKeyCredit;
    }

    public void setPixKeyCredit(String pixKeyCredit) {
        this.pixKeyCredit = pixKeyCredit;
    }

    public Long getTtl() {
        return ttl;
    }

    public void setTtl(Long ttl) {
        this.ttl = ttl;
    }
}
