spring:
  cloud:
    aws:
      sqs:
        endpoint: http://localhost:4566
      sns:
        endpoint: http://localhost:4566
      dynamodb:
        endpoint: http://localhost:4566

payment:
  topic:
    name: arn:aws:sns:us-east-1:000000000000:payment-event