cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    sqs:
      handler:
        default-deletion-policy: never
      listener:
        auto-startup: true
        max-number-of-messages: 10

payment:
  topic:
    name: ${PAYMENT_TOPIC_NAME}